### ISSUE TITLE
Add a new metrics plotter to see how often people will use receiver types.

### ISSUE THREAD

**Issue by licks92** [licks92/WirelessRedstone#102]
Or maybe change the one sending the number of receivers / transmitters / screens to add them in it.

**Comment by Bart-0110** [comment]
Hmmmm mcstats says there's no data

**Comment by licks92** [comment]
Normal. It appears always a few hours later.

**Comment by Bart-0110** [comment]
I think we broke the layout of mcstats xD
http://puu.sh/iygvj/5c9611b437.png

**Comment by licks92** [comment]
LMAO x)

Okay i can log in the website i've registered. But this is seriously way too funny :p

**Comment by licks92** [comment]
Uuh appears normally on my computer.
Still, NO DATA.
I may have done something wrong coding this. But yeah... exams you know (it ends wednesday though and after HOLI-FUCKING-DAYS)

**Comment by Bart-0110** [comment]
Maybe the site can't handle my screen size. I think mcstats needs data from more than a couple hours. Success with your last exams also let me hear if you passed the exams :)

**Comment by licks92** [comment]
What is your screen size exactly? 800x600? :p

**Comment by Bart-0110** [comment]
15 inches

**Comment by licks92** [comment]
I mean... resolution?

**Comment by Bart-0110** [comment]
1366 x 768

**Comment by licks92** [comment]
Okay it is working :)

http://puu.sh/izPN4/fe5295c6a1.png

**Comment by Bart-0110** [comment]
The layout is for me still broken xD

**Comment by licks92** [comment]
Yeah indeed it's happening in the bottom of the page :/ I don't think we can do much about it. I'll try to tweak a few things on my account to see what happens

**Comment by licks92** [comment]
There's already a lot of data for receiver types. Some people may have downloaded our pre builds. Still, it's interesting. I love data.

**Comment by Bart-0110** [comment]
Do you have any idea hat this is:
http://puu.sh/iA7df/75cbffc325.png

**Comment by licks92** [comment]
Uh no. Maybe someone played with the code and sent this data to have fun.
