### ISSUE TITLE
Add /wra restore function

### ISSUE THREAD

**Issue by licks92** [licks92/WirelessRedstone#106]
Not planned for 2.0 though. I think we have enough additions for the next big release already.

**Comment by licks92** [comment]
Meant to use any backup file to restore the signs in the world and the WR database

**Comment by Bart-0110** [comment]
We do have alot of additions.
I made a changelog to keep track of everything
https://github.com/licks92/WirelessRedstone/wiki/Changelog

**Comment by licks92** [comment]
I've seen that ;) But that's the point of using the milestone system. You just have to go in the milestone Version 2.0 and see what issues are closed, and you'll see all the suggestions we've added

**Comment by licks92** [comment]
We only need the last one and it will be okay. But I won't be able to code it tomorrow (last exam)
