### ISSUE TITLE
Error with blockRedstoneEvent

### ISSUE THREAD

**Issue by licks92** [licks92/WirelessRedstone#107]
http://pastie.org/pastes/10255938/text

**Comment by licks92** [comment]
Okay it happens at line 228 of the BlockListener
It's the calling of the BlockRedstoneEvent for 1.8. 
Do you see why it would do that?

**Comment by licks92** [comment]
Maybe we should have tried with latest Spigot. Or maybe his version of Spigot in particular is broken.

But seriously, can't work on this today :(

**Comment by Bart-0110** [comment]
I'll look into it but I think it's not a problem of WR

**Comment by Bart-0110** [comment]
Can't see why it happens so it's invalid

**Comment by licks92** [comment]
Still if it's a problem on his server with one of his plugins we have to make it compatible as soon as possible (when he tells us what plugins he's got installed)

**Comment by Bart-0110** [comment]
Yes but for the time being it's invalid
