### ISSUE TITLE
The switcher receiver

### ISSUE THREAD

**Issue by Bart-0110** [licks92/WirelessRedstone#108]
The switcher receiver : Changes state when the channel is powered. I mean : If the channel is off and the Sreceiver is off, turn on the channel would turn on the Sreceiver. To turn the Sreceiver off, you would have to turn off and turn on again the channel.

@licks92 can you explain it a little bit more?

**Comment by licks92** [comment]
I removed it since I don't find partilarily helpful in the end.

**Comment by Bart-0110** [comment]
Oh, well it's still on the upcomming feuture list

**Comment by licks92** [comment]
I thought i had removed it
