### ISSUE TITLE
New update system

### ISSUE THREAD

**Issue by Bart-0110** [licks92/WirelessRedstone#110]
We should make a new update system. We could do 2 options.

- Make a request to a website and request for the lastest version.
- Try to make it work with bukkit

What do you think @licks92

**Comment by RufiS** [comment]
As a server administrator, I already get update notifications from the Wirelessredstone plugin in the server log and console, frequently enough to update and restart the server just to stop the notifications

**Comment by RufiS** [comment]
And craftbukkituptodate already downloads the updated file for me for easy updating.  I think you time would be better spent elsewhere
