### ISSUE TITLE
Only one sign goes from torch back to sign when more than one are having their state changed at the same time.

### ISSUE THREAD

**Issue by RufiS** [licks92/WirelessRedstone#115]
![2015-06-30_13 21 58](https://cloud.githubusercontent.com/assets/771550/8437387/90ac0e14-1f2c-11e5-89d1-1d973d38bf75.png)
![2015-06-30_13 22 03](https://cloud.githubusercontent.com/assets/771550/8437384/90a83df2-1f2c-11e5-84b9-dadbd08adcaa.png)
![2015-06-30_13 22 08](https://cloud.githubusercontent.com/assets/771550/8437386/90abdb9c-1f2c-11e5-848a-969d9dcdd5b0.png)
![2015-06-30_13 22 15](https://cloud.githubusercontent.com/assets/771550/8437388/90ad6494-1f2c-11e5-812f-aa884e44c788.png)
![2015-06-30_13 22 24](https://cloud.githubusercontent.com/assets/771550/8437385/90ab9f7e-1f2c-11e5-9c8a-38a6559b35c1.png)
![2015-06-30_13 22 27](https://cloud.githubusercontent.com/assets/771550/8437389/90b4630c-1f2c-11e5-9f71-b4d9ff0e8e75.png)
![2015-06-30_13 29 04](https://cloud.githubusercontent.com/assets/771550/8437390/90b6d02e-1f2c-11e5-8b7e-7f0fe27445c9.png)

Noticed when i hooked multiple signs changing states at the same time both receivers will turn on however only one receiver would turn back off.

**Comment by Bart-0110** [comment]
Thank you for your issue. Please can you tell me which version you use? Did you try the last dev build?

**Comment by RufiS** [comment]
Using the latest wirelessredstone and bukkit/spigot 1.8.3
