### ISSUE TITLE
More receiver types

### ISSUE THREAD

**Issue by Coolechriz** [licks92/WirelessRedstone#119]
Hello,

Is there a possibility to make a delay receiver that only will delay when you turn the redstone on and a type that only will delay when you turn off the redstone?

Like this:
- Transmitter+lever > Receiver with a delayon of 10 sec > redstone system 
- Transmitter+lever > Receiver with a delayoff of 5 sec > redstone system

A sign format can be:` [wrr] (channelname) [delayon] (delay in ms)` and `[wrr] (channelname) [delayoff] (delay in ms)`

It would be awesome to see this.

Greats,
CooleChriz

Sorry for my English, this is not my main language

**Comment by Bart-0110** [comment]
Hello,
Thanks for your suggestion. I don't know if I added it to the system. The delayer is a replacement for the repeater. Both work with the a delay when you put them on or off. I have to think about it.

**Comment by Coolechriz** [comment]
Hello,

I know it is a replacement of the receiver. but it would be super convenient because you have more options. I miss this option all times in Minecraft.

**Comment by Bart-0110** [comment]
You can just invert the redstone signal to the transmitter.
