### ISSUE TITLE
Help needed.

### ISSUE THREAD

**Issue by SassinPr0ph3cy** [licks92/WirelessRedstone#124]
Hello, I downloaded the lasted file. Is the Mods folder same as plugins folder? Because when I add the Jar file to my mods folder and launch the game the mod don't show up. currently running Forge 1.8.

**Comment by Bart-0110** [comment]
No the mods folder is NOT the same as the plugins folder. You need to download bukkit, spigot or Cauldron (Bukkit with forge I believe).
