### ISSUE TITLE
Duping Torches [bug]

### ISSUE THREAD

**Issue by CloudeLecaw** [licks92/WirelessRedstone#127]
a user found a bug on Server to dupe torches :D

if u pace a clock or other Receiver on a stair (its a sign) and it turn into the torch then the torch Drops because torches cant be places on stair. on disable the sign is back and you can dupe the next redstonetorch with activating the wireless circuit.

you should block creating recivers on stairs or find a fix for this... :§

**Comment by Bart-0110** [comment]
It's fixed in the new version. I'm planning to push te update somewhere this week.
