### ISSUE TITLE
[Thread-27/ERROR]: [WirelessRedstone] dev.bukkit.org rejected the API key provided in plugins/Updater/config.yml

### ISSUE THREAD

**Issue by agronaque512** [licks92/WirelessRedstone#129]
All in the title, what should i do ?
Here is my config file:

ConfigVersion: 1
Language: fr
ColourfulLogging: true
CheckForUpdates: false
cancelChunkUnloads: true
cancelChunkUnloadRange: 4
UseVault: true
SilentMode: false
DebugMode: false
DropSignWhenBroken: true
InteractTransmitterTime: 1000
CacheRefreshFrequency: 150
gateLogic: OR
saveOption: YML
useSQL: false
MySQL:
  host: ip
  port: '3306'
  database: root
  username: root
  password: password

**Comment by Bart-0110** [comment]
Can you provide me with the full log?
Op 7 nov. 2015 08:05 schreef "agronaque512" <notifications@github.com>:

**Comment by agronaque512** [comment]
Sure here it is:
[00:00:50] [Thread-26/ERROR]: [WirelessRedstone] dev.bukkit.org rejected the API key provided in plugins/Updater/config.yml [00:00:50] [Thread-26/ERROR]: [WirelessRedstone] Please double-check your configuration to ensure it is correct. [00:00:50] [Thread-26/ERROR]: [WirelessRedstone] null

**Comment by Bart-0110** [comment]
This is a problem at bukkit's end. I'm trying to fix it.
