### ISSUE TITLE
Tons of sign copy

### ISSUE THREAD

**Issue by mantricore** [licks92/WirelessRedstone#13]
When I place 3 reciever to activate pistons, each time I activate the lever on the transciever, it make copies of the reviever as a sign ( item ) and drop it evrywhere. The reciever are not destroyed after this operation.

Both three reciever have the same channel.

P= pistons
B=brick
R=Reviever

B B B
P P P
R R R

T= transciever
L=Lever
R=redstone

T R L

**Comment by Bart-0110** [comment]
Should be fixed now, otherwise create a new issue
