### ISSUE TITLE
Transmitter is getting powered when it shouldn't be

### ISSUE THREAD

**Issue by strikerforce** [licks92/WirelessRedstone#131]
When redstone runs past a wireless sign, it receives power from that redstone when it shouldn't. Likewise the same when it is a repeater next to the sign. I attached pictures that show how it reacts in the spigot version and how it reacts in the bukkit version when a repeater is placed next to the signs.

Bukkit Version(Works like it should):
![2015-12-15_20 00 05](https://cloud.githubusercontent.com/assets/8355085/11830601/5b8ea498-a36c-11e5-9acd-c557a7638bc4.png)

Spigot Version (Transmitter is receiving power somehow from the repeater):
![2015-12-15_19 50 41](https://cloud.githubusercontent.com/assets/8355085/11830597/56ee67ca-a36c-11e5-94a1-f792e0ce3a3b.png)

A fix would be amazing as we cannot move from 1.7 without breaking our entire world.

**Comment by Bart-0110** [comment]
I was a little bit inactive but I'll look into it.

**Comment by strikerforce** [comment]
Alright, Thank!

**Comment by Bart-0110** [comment]
It's fixed! You can test it with the lastest dev-build over here:
https://drone.io/github.com/Bart-0110/WirelessRedstone/files
