### ISSUE TITLE
Transmitter is getting powered when it shouldn't be #2

### ISSUE THREAD

**Issue by strikerforce** [licks92/WirelessRedstone#134]
Hey,

The update for the diode has worked splendidly, however, I should have made it explicitly clear in the previous bug report that it does the same thing with redstone wire.

Here is a picture for reference:
![2015-12-18_17 20 44](https://cloud.githubusercontent.com/assets/8355085/11909420/2ad1000c-a5ac-11e5-9101-405c626c4791.png)

Here is how it is suppose to react assuming the transmitter sign is treated like a redstone lamp:
![2015-12-18_17 26 13](https://cloud.githubusercontent.com/assets/8355085/11909457/7be1350c-a5ac-11e5-8d3a-82d9c97166ff.png)
Notice that the lamp is not receiving power from the redstone wire.

However, if we explicitly run the redstone wire to the lamp(sign transmitter):
![2015-12-18_17 28 37](https://cloud.githubusercontent.com/assets/8355085/11909474/d8b89220-a5ac-11e5-8afe-dbad7b04d058.png)
As expected, it is powered.

Your doing an amazing job and I hope this is a simple fix with metadata like the previous one was.

Once again, keep up the great work!

**Comment by strikerforce** [comment]
Refer to my pull request as a possible fix.

**Comment by Bart-0110** [comment]
Thank you for your PR. The redstone logic is orking perfectly! I'm going to merge it with the master branch
