### ISSUE TITLE
Transmitter to receiver breaks connection

### ISSUE THREAD

**Issue by evanmcclan** [licks92/WirelessRedstone#140]
My server is running: CraftBukkit version git-Spigot-1649 (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)

Its running the latest version of wireless redstone.

Problem: Transmitters cant be activated by redstone being powered into the sign, or the block below the sign. Transmitters will only power when a block is placed next to the sign, or if the sign is right clicked. Another problem is that when the transmitter is activated, the receiver only stays active for 1 second before changing back to a sign.

**Comment by Bart-0110** [comment]
Thanks for your report. I'm working on the power issue. 

The other 'problem' is intentional. If you right click a sign it only activates it for a certain amount of time (~1 sec).
