### ISSUE TITLE
1.9 Spigot - Transmission Requires Block Update

### ISSUE THREAD

**Issue by ShrineMaster** [licks92/WirelessRedstone#143]
WR Version 2.6.1
Spigot: 1.9 (built 3/7/2016)

Summary: Signals not transmitted unless there's a block update to any transmitter sign on the channel, and that is only temporary, lasting only a second or two. 

No WR errors in console.  Sign creation and destruction work.  New channels can be created and old destroyed.

**Comment by ShrineMaster** [comment]
I fixed the issue I was having by changing line 224 of WirelessBlockListener.java to include a check for 1.9.

    if (WirelessRedstone.getBukkitVersion().contains("v1_8")) {

changed to:

    if (WirelessRedstone.getBukkitVersion().contains("v1_8") || WirelessRedstone.getBukkitVersion().contains("v1_9") ) {

**Comment by Bart-0110** [comment]
I'll update it
