### ISSUE TITLE
Wireless redstone and 1.10 spigot

### ISSUE THREAD

**Issue by MrKiller01** [licks92/WirelessRedstone#147]
What it is that is wrong, i don't know but the console gives no clue, and the wireless transmitter and/or  receiver does not what they should do.

**Comment by jackmawer** [comment]
The plugin isn't updated to support 1.10 yet.

**Comment by MrKiller01** [comment]
@jackmawer, i know, that's why i reported it so that someone can fix this...(:

**Comment by Bart-0110** [comment]
See #148

**Comment by jackmawer** [comment]
@Bart-0110 Thanks!

**Comment by MrKiller01** [comment]
@Bart-0110  Yeah, thanks you for helping us out...
