### ISSUE TITLE
Works... and doesn't works !

### ISSUE THREAD

**Issue by Minuci** [licks92/WirelessRedstone#151]
Hi !
I downloaded the .jar and put it in the plugins fold. Then I restarted the server and I could place the sign. It says "You just created a new chanel!" and "You just extended a channel!" but when I try to turn on a redstone lamp with a button or a lever... nothing happens...

Can you help me ?

My server is on Spigot 1.8.3 and has those plugins : PlayerHeads, MultiWorld, WorldEdit, SkinsRestorer, Essentials, EssentialsChat, EssentialGeoIP, EssentialsAntiBuild, NoDeathMessage, ViaVersion, EssentialsSpawn, ProtocolLib, DisguiseCraft AND WirelessRedstone

Thank you in advance and sorry for my bad english :D

**Comment by jackmawer** [comment]
Make sure you're powering the WRT sign and you have the WRR sign on your output object. Post any errors in console.

**Comment by Minuci** [comment]
http://puu.sh/pv5So/6b2370a905.jpg

Nothing appears in the console :/

**Comment by jackmawer** [comment]
Try putting the lever right next to the sign

**Comment by Minuci** [comment]
Still doesen't work :/
Is the last version compatible with 1.8.3 ?
Or maybe its a conflict with another plugin...

**Comment by jackmawer** [comment]
Runs fine on 1.8
Make sure your transmitter sign starts with [wrt] and receiver has [wrr]

**Comment by Minuci** [comment]
Still the same...

**Comment by jackmawer** [comment]
Not a clue then. You'll want @Bart-0110 to help you with this one.

**Comment by Minuci** [comment]
Should I contact him or will he be noticed of this message ?

In all cases, thank you ;)

**Comment by jackmawer** [comment]
He'll reply to this issue ticket when he's next available. No need to thank me, I just guided you through the most common troubleshooting steps ;)

**Comment by Minuci** [comment]
Ok ^^

**Comment by Bart-0110** [comment]
Hi,
Can you try to download the latest dev build 
[https://drone.io/github.com/Bart-0110/WirelessRedstone/files](Hyperlink)

**Comment by Minuci** [comment]
That's the one I had... I re-downloaded it and it still doesn't work (even if the "channel" is created) :(

**Comment by Bart-0110** [comment]
Thanks to @Seph29 it works now.
Download the latest dev build ([link](https://drone.io/github.com/Bart-0110/WirelessRedstone/files))

**Comment by Minuci** [comment]
OMG IT WORKS !!!
Thanks you so much :dancers:
