### ISSUE TITLE
Invisible NPC'S

### ISSUE THREAD

**Issue by PIMPCrusader** [licks92/WirelessRedstone#23]
Hi. I like your plugin very much. But since Version 1.6b we have a really big problem. We are using the Citizens Plugin (v1.2) and when we update our wireless redstone to a version above 1.5.2b some npc's are invisible. I search for the plugin which generates this problem and it was wireless redstone. There are no Server Errors or something like an error. Everything seems to be normal. I really hope you can help us, because when this problem doesn't get fixed we must use version 1.5.2b until the version blows up.

We use Craftbukkit 1.2.5-R3.0 and PEX 1.19.2

**Comment by Bart-0110** [comment]
Should be fixed now, otherwise create a new issue
