### ISSUE TITLE
Two problems

### ISSUE THREAD

**Issue by RamTam** [licks92/WirelessRedstone#29]
Hi,
the first thing is, that I can't remove receiver signs. Only by removing the whole channel with /wrremove.
What is the meaning that you can't remove receiver signs but transmitter signs?
Really  irritating because sometimes the whole sign constructure blows up.
And thats the secound issue:
I create a transmitter sign with an channel name and a receiver sign.
It works but after a server restart, I have to place the transmitter signs again because they are out of function o_O

**Comment by Bart-0110** [comment]
Should be fixed now, otherwise create a new issue
