### ISSUE TITLE
2 transmitter and 1 receiver interaction

### ISSUE THREAD

**Issue by bukkiteclipse** [licks92/WirelessRedstone#31]
If you put 1 receiver and 2 transmitter signs
and for example connect 1 lever to each transmitter now you have to put the levers on. After that you have to put 1 of them to off, the result: the receiver goes from on to off although 1 transmitter is getting powered.(sometimes it blinks once additionally before getting off) 

This problem seems not to happen alot, but it cost me alot of work to bypass this on my last restone project, that has to do with counterdisplays.
And i guess this was also not designated, cause normal Redstone doesnt behave like this.
Or does the transmitters sum up and represent an AND-GATE ? but again actually i think it shouldnt cause GATES have nothing to do with normal Redstone"ways"

I also maybe have 1 solution-idea for that one:
I think this has to do with updating, the updating on the channel is not fully given(again i just think so, but you are the one to find out and solve this)

I would love, if you could fix this one(besides some null-pointer-issues, that are already reported by others)

(but Wireless Redstone made my Life better, i cant without it anymore ;) so keep the good work up)

**Comment by Bart-0110** [comment]
Accidently fixed xD

**Comment by Bart-0110** [comment]
It's fixed
