### ISSUE TITLE
Failure depending on the surface the reciever is placed on.

### ISSUE THREAD

**Issue by bob123412** [licks92/WirelessRedstone#45]
Wirless redstone version: 1.7b
Craftbukkit version:git-Bukkit-1.4.2-R0.1-3-gff87b97-b2450jnks (MC: 1.4.2)

My issue is I have a lever that is connected to a transmitter that has 20+ recievers connected to it which then Send a signal to another 20+ transmitters to even more recivers which turn on/off lights and open/close doors, or atleast that is what is supposed to happen. What acctually happens is it lags (which it should other wise I hooked somthing up wrong), then breifly powers the recievers and then turns the power off even though the lever is still powering the transmitter.

Also when I use a diffrent transmitter which is connected to the same system except on a flat surface instead of a wall it works.

**Comment by Bart-0110** [comment]
Should be fixed now, otherwise create a new issue
