### ISSUE TITLE
Track switching and receiver signs

### ISSUE THREAD

**Issue by RufiS** [licks92/WirelessRedstone#46]
I noticed the other day, if you have a three track intersection where, two the the tracks are on the same level, and the third is one block lower, a receiver sign when turned on and off, will not cause the track to switch.  It is required that you move the sign back one square and put down a redstone wire connecting the receiver sign and the track intersection. S,sign, r, redstone dust, T, track.
   T
   T
SrTTTT
   T
   T
git-Bukkit-1.4.7-R1.0-5-g6c77179-b2629jnks (MC: 1.4.7)
Wireless Redstone 1.8.4b

**Comment by Bart-0110** [comment]
It's working for me. Create a new issue if you still have this problem
