### ISSUE TITLE
Server Crash and all channels gone.

### ISSUE THREAD

**Issue by johano1rct** [licks92/WirelessRedstone#52]
My server has about 600+ channels in total, And yesterday the server crashed on these errors:

http://pastebin.com/2fJg5Jux
http://pastebin.com/7RVTr5vA

After I rebooted the server ALL channels were gone. All of them. I use YAML storage. Not sure if I did something wrong, I was just making Wrr and Wrt's like I always do.

**Comment by Bart-0110** [comment]
We can't really fix this issue due to Java. If a file is opened and save constantly and the server crashes it will save it incorrectly
