### ISSUE TITLE
The same error being spammed for having screens which were broken by nature.

### ISSUE THREAD

**Issue by iMagic16** [licks92/WirelessRedstone#53]
Sunday May 26 3:25:40 AM [INFO] [WirelessRedstone][SEVERE] Error while updating redstone onBlockRedstoneChange for Screens , turn on the Debug Mode to get more informations.

The above gets spammed into my console almost 24/7 non-stop. It'll occasionally stop, but since we use WiRe for a day/night lighting system (reverse light sensor connect to wrt, etc) the destroyed screens keep trying to activate, I guess causing this error.

I have a few 1000 channels I do not wish to reset...

They were either destroyed by TNT or water/lava (knowing my friends)

This causes significant lag for my server, where removing it increases ping massively and server responds 5x faster.

CraftBukkit 1.5.1 alpha (previously, problem started here)
CraftBukkit 1.5.2 beta (problem persists here)
WiRe 1.8.6b (updated from old 147 version and problem persists)

**Comment by Bart-0110** [comment]
Should be fixed now, otherwise create a new issue
