### ISSUE TITLE
WorldEdit

### ISSUE THREAD

**Issue by jwroczynski** [licks92/WirelessRedstone#56]
I've got one, but big issue... When I copy some blocks with receivers (WorldEdit) - receivers doesn't work ! But, when I destroy receiver then the message "Successfully removed this sign !" is on the chat. It'll be more comfortable for WorldEdit and WirelessRedstone's users.

**Comment by Onoitsu2** [comment]
I think this copy and paste is relating to world edit lacking the ability to properly copy nbt tags. If it could, then any imported schematic that has writing on the signs would have the same writing, not be blank.
