### ISSUE TITLE
Sign on chanel '...' broken by Nature

### ISSUE THREAD

**Issue by totoberg123** [licks92/WirelessRedstone#58]
Hello, today im creating a theme park in Minecraft and use TrainCarts, Essentials, World Edit, WaterProofRedstone, AntiLeafDecay and WirelessRedstone.
 Everytime i create a channel and place Receivers and Transmitters, after a little time i get a Notice in the chat that 'My sign on chanel .. is broken by nature' !

If i found the Receiver its still placed and text on the sign etc. But its not working anymore..

Could you please fix this or help me? Thanks!

**Comment by Bart-0110** [comment]
Should be fixed now
