### ISSUE TITLE
Idée pour la prochaine

### ISSUE THREAD

**Issue by Kervinou** [licks92/WirelessRedstone#65]
Hi!
Avoir un purge possble pour les admins pour effacer par exemple les canaux qui n'ont pas receiver+emetteur
++
ps: 1.9 installée ce matin

**Comment by licks92** [comment]
Let me translate this for my collaborator : 
Request is to add a command like /wr admin purge that will scan the database and remove empty channels, but also signs that exist in the data but no longer in the real world.
This in interesting. I put it for WR 2.0
