### ISSUE TITLE
nullpointerexception error on startup

### ISSUE THREAD

**Issue by Firstgamefreak** [licks92/WirelessRedstone#70]
Upon starting my server I came up with this error when i started my server. I installed vault as well but i didn't help at all. My server and client version are 1.6.4 and i use craftbukkit-1.6.4-R2.0. My wirelessRedstone version is v1.9.1. The error along with my entire server startup is located here http://pastebin.com/F5Q3zLFm

**Comment by Bart-0110** [comment]
Should be fixed, please make a new issue if it still happens
