### ISSUE TITLE
Error given

### ISSUE THREAD

**Issue by LazyUmpire** [licks92/WirelessRedstone#72]
I don't know why this happened by WRR has stopped working.
I'm running CB Beta 1.7.2-R0.2

Error:
19.01 20:48:35 [Server] INFO [20:48:35 WARN]: 	at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617)
19.01 20:48:35 [Server] INFO [20:48:35 WARN]: 	at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:457)
19.01 20:48:35 [Server] INFO [20:48:35 WARN]: 	at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:545)
19.01 20:48:35 [Server] INFO [20:48:35 WARN]: 	at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:250)
19.01 20:48:35 [Server] INFO [20:48:35 WARN]: 	at net.minecraft.server.v1_7_R1.MinecraftServer.u(MinecraftServer.java:629)
19.01 20:48:35 [Server] INFO [20:48:35 WARN]: 	at net.minecraft.server.v1_7_R1.WorldServer.doTick(WorldServer.java:205)
19.01 20:48:35 [Server] INFO [20:48:35 WARN]: 	at net.minecraft.server.v1_7_R1.WorldServer.a(WorldServer.java:532)
19.01 20:48:35 [Server] INFO [20:48:35 WARN]: 	at net.minecraft.server.v1_7_R1.BlockRedstoneTorch.a(BlockRedstoneTorch.java:147)
19.01 20:48:35 [Server] INFO [20:48:35 WARN]: 	at net.minecraft.server.v1_7_R1.World.setTypeAndData(World.java:304)
19.01 20:48:35 [Server] INFO [20:48:35 WARN]: 	at net.minecraft.server.v1_7_R1.World.update(World.java:407)
19.01 20:48:35 [Server] INFO [20:48:35 WARN]: 	at net.minecraft.server.v1_7_R1.World.applyPhysics(World.java:435)
19.01 20:48:35 [Server] INFO [20:48:35 WARN]: 	at net.minecraft.server.v1_7_R1.World.e(World.java:486)
19.01 20:48:35 [Server] INFO [20:48:35 WARN]: 	at net.minecraft.server.v1_7_R1.BlockSign.doPhysics(BlockSign.java:123)
19.01 20:48:35 [Server] INFO [20:48:35 WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:466)
19.01 20:48:35 [Server] INFO [20:48:35 WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:481)
19.01 20:48:35 [Server] INFO [20:48:35 WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
19.01 20:48:35 [Server] INFO [20:48:35 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
19.01 20:48:35 [Server] INFO [20:48:35 WARN]: 	at java.lang.reflect.Method.invoke(Method.java:601)
19.01 20:48:35 [Server] INFO [20:48:35 WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19.01 20:48:35 [Server] INFO [20:48:35 WARN]: 	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
19.01 20:48:35 [Server] INFO [20:48:35 WARN]: 	at net.licks92.WirelessRedstone.Listeners.WirelessBlockListener.onBlockRedstoneChange(WirelessBlockListener.java:165)
19.01 20:48:35 [Server] INFO [20:48:35 WARN]: 	at net.licks92.WirelessRedstone.Channel.WirelessChannel.turnOn(WirelessChannel.java:108)
19.01 20:48:35 [Server] INFO [20:48:35 WARN]: 	at net.licks92.WirelessRedstone.Channel.WirelessReceiver.turnOn(WirelessReceiver.java:220)
19.01 20:48:35 [Server] INFO [20:48:35 WARN]: 	at org.bukkit.material.Sign.getFacing(Sign.java:145)
19.01 20:48:35 [Server] INFO [20:48:35 WARN]: java.lang.NullPointerException
19.01 20:48:35 [Server] INFO [20:48:35 INFO]: [WirelessRedstone][SEVERE] Error while updating redstone event onBlockRedstoneChange for Receivers. Turn on the Debug Mode to get more informations.

**Comment by Bart-0110** [comment]
Should be fixed now
