### ISSUE TITLE
How to mass WirelessRedstone : auto-create channel

### ISSUE THREAD

**Issue by crunkazcanbe** [licks92/WirelessRedstone#75]
I have a idea that would make the end user experience better. Is it possible you could make it to where it automatically assigns a number for the signs to where all you have to put on the sign is [transmitter] or [receiver] and it will automatically assigns a number that's not used . 

Because trying to remember what ids i have already used is almost impossible considering i have a few hundred transmitters and receivers . You could make it to where you could manually put the id in if you want more then one of the same transmitter or receive.

**Comment by Bart-0110** [comment]
Quick tip: you can also use some letters, e.g. test123. But watch out with using special characters.

**Comment by licks92** [comment]
Okay here's how I see this : 
Maybe we could add the following pattern : 
[WirelessPoint]
[auto]

Which will instantly create a channel with a random name.

Or maybe [Wirelesspoint]
.

Since the dot is currently an unauthorized character, it could be used for this purpose, what do you think?

**Comment by Bart-0110** [comment]
Why wirelesspoint though.
Maybe it's easier to just use [wrr] etc.
And I think that we should go with [auto]

**Comment by licks92** [comment]
Oh yeah I just wrote it so it could mean [wrr] or [wrt] or [wrs]
Since in the code they all derive from IWirelessPoint

**Comment by Bart-0110** [comment]
Should we turn it to an auto-increment integer system?
That means that it check if channel '1' exist and then make a new channel with the name '2'
Or should we do auto-increment string system?
Check for channel 'a' if exist create 'b' and go further (at the and it should make this 'z' then 'aa')

My vote is for the auto-increment integer

**Comment by licks92** [comment]
Yeah that's better. I'd rather call each channel... ch_1, ch_2, ch_3 or sthg like that. But increment the numbers, not letters (numbers are easier to understand, it's universal)
