### ISSUE TITLE
Panneau WRr bloqué en position ON

### ISSUE THREAD

**Issue by Kervinou** [licks92/WirelessRedstone#77]
Un de mes ponts reste bloqué en position ON

Je m'en suis rendu compte car les leviers ne fonctionnaient plus, j'ai donc cassé autour pour voir d'où cela pouvait venir et je me suis rendu compte que même avec ma hache, le panneau reste en position ON et est incassable.

Ce n'est pas la première fois depuis que tu avais mis à jour, habituellement, je refais les panneaux, mais là, je me dit qu'il serait peut être intéressant que tu vois pour éventuellement corriger car je ne dois pas être le seul à qui cela arrive.

Avant d'aller plus loin et de forcer sa casse, j'ai préféré laisser en l'état dès fois que tu veuilles voir ce que ça donne

Tu as déjà ton compte, donc tu peux te connecter quand tu veux pour voir: il s'agit de la porte Nord
Si besoin, nous sommes souvent connecté le soir et souvent sur le TS, tu as le lien en signature normalement ;)

Merci
A bientôt
Kerv.++

**Comment by Bart-0110** [comment]
Can you translate it to English please. I do not understand French :/

**Comment by Kervinou** [comment]
Not important
i was writing in french cause autor is a french guy

but since 1 year, i dont use this plugin anymore to force people to be better in redstone ;)
and me too ! ;)

thanks
