### ISSUE TITLE
Missing MySQLStorage - Some coding info

### ISSUE THREAD

**Issue by chaos234** [licks92/WirelessRedstone#78]
Hiho,

I've forked this nice plugin but was shocked because there is only a unfriendly support of sqllite which isn't a good choise.

So I actually write a MySQLStorage because it's much better because you can look into the table and if they are marked as "locekd/broken" you can repair then over phpMyAdmin.

Second one is the coding style ... I've to recreate all breackets because it's false to put them in the next line ... one example:

FALSE (can't read such a construction of code):

if ((statement == true)
    || statement2 != null)
{
   //do nice stuff
}

CORRECT (Better to read and better to understand :)):

if ((statement == true) || (statement2 != null)) {
  //do nice stuff
}

Oh ... at some if-statements I found some necessary semikolons (;) and removed them and in the plugin.yml are a double entry for wrr :).

Hope I get the MySQLStorage working with better performenc as Yamle-/SQLLite-File.

Regards
Chaos234
(MC-Nick: Chaoschaot234)

**Comment by licks92** [comment]
Okay I take it into account. The thing is : I never really worked with sql before that so i admit the code may be messy. I'll do what I can.

**Comment by rautamiekka** [comment]
It's not even necessary nor useful to write `if ((statement == true) || (statement2 != null))`, just do `if (statement == true || statement2 != null)`.
