### ISSUE TITLE
WRW-Signs does't "ask" corect Position

### ISSUE THREAD

**Issue by Chaos234** [licks92/WirelessRedstone#80]
It's horrible tht this plugin has no listener to the Position of the WRR-Sign to change it correctly with a powered torch!

Because this is mising, the sign blws up and the tourch dissapears and after the signal at the wrt is gone away the WRR-Sign juped at the false block (e. g. a = redstone lamp and b = wood ... know I place the WRR at b and power/depwoer the wrt now the wrr is at a instead of b which is false!)

I hope this would be fixed in the next few days and not in a year!

**Comment by licks92** [comment]
Technically it's been a year :D okay i should not laugh. I'm working on it.

**Comment by licks92** [comment]
Okay this has been fixed by commit 260 or before.
