### ISSUE TITLE
Suggestion - teleport to a specified channel name

### ISSUE THREAD

**Issue by gamelover1985** [licks92/WirelessRedstone#83]
wr list gives me all the available channels

wr tp (channel name R) or (Channel name T) takes me to either a transmitter or receiver

The issue i have right now is i can't find like 17 levers i hid all over my map... this sucks dookie :p but whatever. Now I can't use the levers+ plugin i got to assign to each lever to auto flip it on or off... sucks even more dookie :p really wish i could find those levers but hid them so so well on my map they are gone forever... and now there is no way to modify my parkour course which is very very very very long... a 6 hour course with tons of levers... no redstone trail to follow its all just wonderful wireless redstone--so once we lose our precious transmitter spots or receiver spots--they are gone forever :( its so sad.

Wish there was a way to tp to my created channels :(

**Comment by licks92** [comment]
But that's a good suggestion.

**Comment by licks92** [comment]
Okay so this suggestion has been implemented. I close it
