### ISSUE TITLE
auto on off transmitter

### ISSUE THREAD

**Issue by gamelover1985** [licks92/WirelessRedstone#84]
a transmitter that turns on an off automatically by itself and goes on forever even if a player isn't near by? If not then just if a player is near by then. Minecarts work fine to allow pistons to push in and out but with the new minecraft updates now the minecarts stop if a player isn't close by. Try to keep the minecarts in close enough range so the pistons will go in and out when a player is close by on my parkour course, but it fails. But if it was a sign that was directly next to where the players were then hey that would work great :D

Like, i choose in ms how long it turns on for, then in ms how long before it shuts off again.

**Comment by licks92** [comment]
Like a clock? We're adding right now.

**Comment by Bart-0110** [comment]
Done. It will be available at release 1.9.6

**Comment by licks92** [comment]
2.0*
