### ISSUE TITLE
Names

### ISSUE THREAD

**Issue by Tranny** [licks92/WirelessRedstone#86]
Hey! I just downloaded Wireless Redstone and must say, It's very neat and I really enjoy it! I have only one problem with it and it's quite a pester to say the least. I checked all the other plugins and it happens to be this one. When I have this plugin, it automatically deletes all of the players nicknames and changes the color of their names to black. Any idea why this is or how to fix it? Thanks so much!

**Comment by licks92** [comment]
I have nooooo idea...

**Comment by licks92** [comment]
But yeah, too old. Open it again if you still use it and still got this bug.

**Comment by avalonv** [comment]
RIP tranny you were a real one
