### ISSUE TITLE
CommandBlock integration

### ISSUE THREAD

**Issue by skittishtrigger** [licks92/WirelessRedstone#90]
Using latest 1 spigot server when issuing a command (wr activate name time) the command does not function (works perfectly from chat box. Looking at server console out put it says only in game players can use this command. Is this a bug or an intentional thing?

**Comment by licks92** [comment]
I don't really know. Never tried. I looked after. Put it in suggestion, as it could be a new functionnality

**Comment by licks92** [comment]
I'm gonna do it

**Comment by licks92** [comment]
Okay I'm beginning the work on this

**Comment by licks92** [comment]
I think there are 3 types of commands : those that can be executed by players, those that can be executed by players and console, and those that can be executed by players, console and commandblocks.

I will define what commands should be executed by who.

Also, if we do this, I'm thinking about adding a option in the config about allowing the commandBlocks or not.

**Comment by Bart-0110** [comment]
Console and commandblocks are pretty much the same maybe we should do 2 types

**Comment by licks92** [comment]
distinguished the two.

Here it is : CBlocks are only allowed to activate and lock a channel, since they are not manned.
Console is manned, so it will be allowed to use everything but /wrt /wrs /wrr and /wrtp which are ofc only usable by people.

**Comment by licks92** [comment]
I don't want a wild command that someone didn't remove to be able to wipe all data all of a sudden

**Comment by licks92** [comment]
So I'm doing the commits on my computer but not pushing for the moment, not until i'm sure this is a all working smoothly

**Comment by Bart-0110** [comment]
Okey. Quick tip: you can create commits in intellij and push them (and almost everything else)

**Comment by licks92** [comment]
Yeah but I like the github app interface ;) thanks though

**Comment by licks92** [comment]
Compiled on my pc. I'm running tests but I should push normally in a few minutes

**Comment by licks92** [comment]
Test runned fine. Push'd and closed
