### ISSUE TITLE
Setup question

### ISSUE THREAD

**Issue by Bart-0110** [licks92/WirelessRedstone#92]
Can you give me write access? Thanks and can you also PM me your skype

**Comment by licks92** [comment]
PR should be easier as we have to merge everything first...
Is your skype Bart-0110?

**Comment by Bart-0110** [comment]
No it's bart.denhamer
I didn't change anything though so it isn't needed to merge it

**Comment by licks92** [comment]
Wait, you don't want to merge your fork? There's some pretty good things on it (well I didn't really look at the code in detail but looks okay)

**Comment by licks92** [comment]
Installing skype too

**Comment by Bart-0110** [comment]
I reverted it because I had to look how it worked

**Comment by Bart-0110** [comment]
And you pust an update on your own fork and I can't get it

**Comment by Bart-0110** [comment]
So it will override it

**Comment by licks92** [comment]
Normally there's a way to merge everything without overriding. Git knows how to fix this. But we should talk on skype. Wait a minute...
