### ISSUE TITLE
Apparently the receivers using a time value don't care for that value

### ISSUE THREAD

**Issue by licks92** [licks92/WirelessRedstone#94]
Meaning : Put any clock or delayer with a value of in example 1000 ms, it will actually use 0 ms as a value.

Fun fact : using this with the last bug allows to create clocks on wall that spawn redtorches incredibly fast

**Comment by licks92** [comment]
Plus : Issue only with yaml storage. We can't put YAML aside for the moment, way too interesting for people who like to change the DB instantly or to look into it quickly.

So we have to fix this.

**Comment by Bart-0110** [comment]
The delay and the clock are working for me.

**Comment by licks92** [comment]
With yaml storage?

**Comment by Bart-0110** [comment]
Nm didn't saw your first comment

**Comment by licks92** [comment]
Okay, fixed by the latest commit (271 I think)
