### ISSUE TITLE
Crash at launch with a yaml storage

### ISSUE THREAD

**Issue by licks92** [licks92/WirelessRedstone#95]
[23:24:20 ERROR]: Error occurred while enabling WirelessRedstone v1.9.6 (Is it u
p to date?)
java.lang.NullPointerException
        at net.licks92.WirelessRedstone.WirelessRedstone.LoadChunks(WirelessReds
tone.java:311) ~[?:?]
        at net.licks92.WirelessRedstone.WirelessRedstone.onEnable(WirelessRedsto
ne.java:157) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[s
pigot.jar:git-Spigot-44c59bf-8f0f4ed]

Apparently linked to the cache not loading correctly the receivers locations into it.

**Comment by Bart-0110** [comment]
When does this happen? I have a yaml storage and it runs normally

**Comment by licks92** [comment]
Have a storage yaml with channels, reboot the server, it should happen.

**Comment by Bart-0110** [comment]
First run nothing..
Second run nothing..
Third run nothing..

**Comment by licks92** [comment]
I will try tonight to reproduce it

**Comment by Bart-0110** [comment]
Oh maybe I know it. You probably had some channels inside yaml storage convert it to db storage.
I already fixed it, [commit](https://github.com/licks92/WirelessRedstone/commit/7f51ad42f9507b69cbbf22bcc48700cacdb6364c)

**Comment by Bart-0110** [comment]
I'm gonna close it because I can't get the error. Reopen if it still throw an error
