### ISSUE TITLE
Bug spams server

### ISSUE THREAD

**Issue by diamondpumpkin** [licks92/WirelessRedstone#96]
Every 14 seconds these messages come up:
18.06 19:55:40 [Server] INFO [WirelessRedstone] A new version has been uploaded on the repository! I highly recommend you to download it now on http://dev.bukkit.org/server-mods/wireless-redstone/
18.06 19:55:16 [Server] INFO [WirelessRedstone] A new version has been uploaded on the repository! I highly recommend you to download it now on http://dev.bukkit.org/server-mods/wireless-redstone/
18.06 19:54:52 [Server] INFO [WirelessRedstone] A new version has been uploaded on the repository! I highly recommend you to download it now on http://dev.bukkit.org/server-mods/wireless-redstone/
18.06 19:54:28 [Server] INFO [WirelessRedstone] A new version has been uploaded on the repository! I highly recommend you to download it now on http://dev.bukkit.org/server-mods/wireless-redstone/

I'm am on 1.7.10 and it wants me to update to 1.8.X when which I do the plugin's main feature doesn't work. When I send a signal through the wirelessredstone the other end just makes it a torch and doesn't place it... Please fix this so the server isn't getting spammed!

**Comment by Bart-0110** [comment]
Simply disable the updater.
But can you explain a little bit more why the receivers aren't working

**Comment by diamondpumpkin** [comment]
That's the problem, there's no "checkForUpdates"

**Comment by licks92** [comment]
It is in the Updater folder not in wirelessredstone

**Comment by diamondpumpkin** [comment]
Ahh

**Comment by diamondpumpkin** [comment]
Looks like it's fixed. Thanks

**Comment by Bart-0110** [comment]
Np we like to help and improve our plugin
